// Generated by backend/scripts/curate-top-picks.mjs -- do not hand-edit.
// Re-run the script + redeploy to refresh homepage picks.
export const topPicks: string[] = [
  "prod_01M3NM59VFJTWSQNA6E2P9WWQ3",
  "prod_01M3NM59VFJ8XEEG8QR5MMJYYW",
  "prod_01M3NM59VFQRWF9AA27P4F3N9P",
  "prod_01M3NM59VFDQGTXN9YKWYSTECS",
  "prod_01M3NM59VFZ0QSC9WFFG8BC3FV",
  "prod_01M3NM59VFH8K208527FQ9PFT1",
  "prod_01M3NM59VFAQPAXY6PRGRX4E3P",
  "prod_01M3NM59VF8A1J8J2QGC3EW2ME",
]
